/** Todas las rutas del portal en un solo lugar. */
export const paths = {
  login: '/entrar',
  apply: '/postular',
  application: '/solicitud',
  admissions: '/solicitudes',
  assistedApplication: '/solicitudes/nueva',
  admission: (applicationId: string) => `/solicitudes/${encodeURIComponent(applicationId)}`,
  home: '/',
  places: '/lugares',
  place: (stopId: string) => `/lugares/${encodeURIComponent(stopId)}`,
  coupons: '/cupones',
  events: '/eventos',
  badges: '/insignias',
  billing: '/pagos',
  organizations: '/organizaciones',
  organization: (organizationId: string) => `/organizaciones/${encodeURIComponent(organizationId)}`,
  collections: '/cobros',
  pricing: '/tarifas',
  guides: '/guias',
  guideApplication: (applicationId: string) => `/guias/${encodeURIComponent(applicationId)}`,
  users: '/usuarios',
  staff: '/usuarios/equipo',
  staffRoles: '/usuarios/roles',
} as const
