/** Todas las rutas del portal en un solo lugar. */
export const paths = {
  login: '/entrar',
  resetPassword: '/restablecer',
  invitation: '/invitacion',
  security: '/seguridad',
  apply: '/postular',
  application: '/solicitud',
  correctApplication: '/solicitud/corregir',
  admissions: '/solicitudes',
  admission: (applicationId: string) => `/solicitudes/${encodeURIComponent(applicationId)}`,
  home: '/',
  places: '/lugares',
  place: (stopId: string) => `/lugares/${encodeURIComponent(stopId)}`,
  circuits: '/circuitos',
  newCircuit: '/circuitos/nuevo',
  circuit: (circuitId: string) => `/circuitos/${encodeURIComponent(circuitId)}`,
  coupons: '/cupones',
  events: '/eventos',
  badges: '/insignias',
  billing: '/pagos',
  organizations: '/organizaciones',
  organization: (organizationId: string) => `/organizaciones/${encodeURIComponent(organizationId)}`,
  collections: '/cobros',
  withdrawals: '/retiros',
  pricing: '/tarifas',
  reviewDisputes: '/resenas',
  guides: '/guias',
  guideApplication: (applicationId: string) => `/guias/${encodeURIComponent(applicationId)}`,
  users: '/usuarios',
  staff: '/usuarios/equipo',
  staffRoles: '/usuarios/roles',
  reports: '/reportes',
  sanctions: '/sanciones',
} as const
